name: pkgcheck

# This will cancel running jobs once a new run is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  # Manually trigger the Action under Actions/pkgcheck
  workflow_dispatch:
  # Run on every push to main
  push:
    branches:
      - main
      - master

jobs:
  pkgcheck:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    env:
      OPENFDA_KEY: ${{ secrets.OPENFDA_KEY }}
      OPENFDA_TOKEN: ${{ secrets.OPENFDA_TOKEN }}
    steps:
      - uses: ropensci-review-tools/pkgcheck-action@main
